### ISSUE TITLE
Remove tracking query parameters

### ISSUE THREAD

**Issue by ranjithrajv** [bromite/bromite#1805]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

→ LibreWolf
I've requested the same feature for LibreWolf Desktop Browser, they've recently implemented it.
(https://gitlab.com/librewolf-community/settings/-/issues/128)

→ Brave
You can refer to Brave's implementation of it here: https://github.com/brave/brave-browser/wiki/Query-String-Filter

Brave's default list might be a good starting point → https://github.com/brave/brave-core/blob/f337a47cf84211807035581a9f609853752a32fb/browser/net/brave_site_hacks_network_delegate_helper.cc#L29

### Describe the solution you would like

[Privacy Tests](https://privacytests.org/) (Open-source tests of web browser privacy) did a good job in listing all the privacy tests reports of popular browsers. Bromite is the go-to choice for mobile browsers, as one of the privacy assuring browsers in the era of surveillance capitalism. Appreciate the efforts of the team behind Bromite for the great work you are doing.

But the only section Bromite  needs to improve is, removing tracking query parameter tests. If this is done, it will be a good PR slogan for Bromite to say most privacy-assuring browsers for Android. I wish Bromite to achieve multifold increase in user-base, in near future.

→ What are Tracking query parameter tests
When you browse from one web page to another, tracking companies will frequently attach a 'tracking query parameter' to the address of the second web page. That query parameter may contain a unique identifier that tracks you individually as you browse the web. And these query parameters synchronized with cookies, making them a powerful tracking vector. Web browsers can protect you from known tracking query parameters by stripping them from web addresses before your browser sends them.

### Describe alternatives you have considered

Tried forks of Firefox, but they need to implement these features too.

**Comment by kokukyocho** [comment]
Hello @ranjithrajv!

I am a bot :robot:

Thanks for submitting this issue!
I noticed that it is missing the template, please edit the issue to match the template for either a [bug](https://github.com/bromite/bromite/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) or a [feature request](https://github.com/bromite/bromite/blob/master/.github/ISSUE_TEMPLATE/feature_request.md); the issue will be automatically re-opened afterwards.

If this is not an issue nor a feature request and you want to start a discussion then you can use [GitHub Discussions](https://github.com/bromite/bromite/discussions).

**Tip**: if you use GitHub in Desktop mode the template will be proposed to you when submitting issues.

**Comment by uazo** [comment]
already requested other times https://github.com/bromite/bromite/issues/1228 https://github.com/bromite/bromite/issues/661 I think the answer is always the same, which is to use userscripts.

I also add that I think that a useragent should never modify a user's navigation, unless it is possible by w3c standards, but I am not aware of it.
currently bromite denies or reduces features, does not load resources with the ads blocker, but never modifies addresses, to say, when you browse a site it is definitely what you entered (as chrome, and since there are a lot of professionals behind chrome, I consider it a guarantee).

notice: I would like to develop it too, but it could be dangerous to modify the url so it must be a risk that the user takes independently, there is no certainty of not introducing any new vulnerabilities.

obviously this is my opinion, then @csagan5 will give you the official one, and if a secure way is found I will be very happy to implement it.

**Comment by csagan5** [comment]
Yes @uazo gave a good explanation.

I am not against this functionality but it has to be stand-alone, best done with UserScripts; it would be a project on its own to maintain it and I cannot commit to it.

Plus, thanks to the UserScripts that @uazo added anybody can start creating and maintaining this sort of "plugin" and use it.
