### ISSUE TITLE
Epic launcher fails to load, reverts offline mode 

### ISSUE THREAD

**Issue by Reporter1** [bromite/bromite#2041]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md).
- [X] I have searched the existing issues for my problem. This is a new ticket, NOT a duplicate or related to another open issue.
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have updated Bromite to the latest version. The bug is reproducible on this latest version.

### Can the bug be reproduced with corresponding Chromium version?

No

### Bromite version

Latest from fdroid 101.0.4951.53

### Device architecture

arm64

### Android version

12

### Device model

Pixel 5 

### Changed flags

N/a

### Is this bug about the SystemWebView?

Yes

### Is this bug happening in an incognito tab?

No

### Is this bug caused by the adblocker?

No

### Is this bug a crash?

No

### Describe the bug

Unable to install and access Fortnite via epic launcher. Epic launcher is available on the url https://www.epicgames.com/fortnite/en-US/mobile/android/get-started

I examined the logcat and noticed a webview entry, which I then decided to change bromite webview to android (play store) Web view, I retired and epic game app open and shows the content. 

Swapping webview to bromite breaks the content view and confirms its to do with bromite.

I have installed chromium webview and have no issues with it, although 
Has the same name as the stock android, Android System Webview 
![Screenshot_20220503-091744_Settings_1](https://user-images.githubusercontent.com/34857551/166423929-6bc27d6e-da89-46ed-9f97-674e930d6292.png)

### Steps to reproduce the bug

1. Ensure bromite system view is enabled and selected in phone settings, system, developer settings, webview  implementation 
2. open url [https://www.epicgames.com/fortnite/en-US/mobile/android/get-started](https://www.epicgames.com/fortnite/en-US/mobile/android/get-started) 
3. Select get it on epic games app download link
4. Download apk
5. Install apk, if using browser prompt to Install apk, allow unknown sources when prompted to be able to install apk 
6. Launch epic games app
7. Observe blank screen, or app will direct loop to default browser loop back and forth to epic launcher app.
8. If you see black screen you can swipe down and you will see pull to refresh like a Web site and suddenly you will see a spinning loading circle. L

### Expected behavior

Once epic launcher app is installed, open epic games app and expect to see fortnite install options. 

### Screenshots

#
![Screenshot_20220502-002716_Epic Games](https://user-images.githubusercontent.com/34857551/166419511-7ae47092-e209-4111-b85a-97000f0bfa16.png)
![Screenshot_20220503-081311_Epic Games](https://user-images.githubusercontent.com/34857551/166419531-2697d39c-ab52-4ea6-98bd-98cb97c7647f.png)

**Comment by Reporter1** [comment]
Fortnite screenshot working in chromium and stock android webview. 
![Screenshot_20220503-093054_Epic Games_1](https://user-images.githubusercontent.com/34857551/166424552-0b131d50-b6a1-4e85-b721-5775e542faf8.png)

**Comment by csagan5** [comment]
> Swapping webview to bromite breaks the content view and confirms its to do with bromite.
> 
> I have installed chromium webview and have no issues with it, although

As you noticed in the issue template and FAQs there is no support for the SystemWebView; if you are willing to troubleshoot the issue further and debug it then I can leave this issue open.
