### ISSUE TITLE
Remove Instagram's igsh share tracker

### ISSUE THREAD

**Issue by futurk** [bromite/bromite#2660]
### Preliminary checklist

- [X] I have read the [README](https://github.com/bromite/bromite/blob/master/README.md)
- [X] I have read the [FAQs](https://github.com/bromite/bromite/blob/master/FAQ.md).
- [X] I have searched [existing issues](https://github.com/bromite/bromite/issues) for my feature request. This is a new issue (NOT a duplicate) and is not related to another issue.
- [X] This is a feature request for the Bromite browser; not the website nor F-Droid nor anything else.

### Is your feature request related to privacy?

Yes

### Is there a patch available for this feature somewhere?

https://github.com/brave/brave-browser/issues/35094

### Describe the solution you would like

Big tech platforms like YouTube, Instagram, X - love to append a tracker id to their URLs in order to track people across the web.
This issue basically leads to two cases:
1. When user opens the link via Bromite, tracker part should be removed before the navigation starts (i.e., before GET request is sent).
2. When user wants to share the link, tracker part should not be included.

### Describe alternatives you have considered

Modify the request headers OR modify the URL
before sending
